add phone icon & disable news label if no news
bouncmpe/hugo-theme-department pull request #1
Opened 2023-07-05 19:43 UTC by furkanakkurt1335

- Added the telephone icon.
- Added condition not to show news label on home page if there are no news.

2023-07-06 06:59 UTC, doganulus requested changes
Two comments:
1. It is better if the `if` block contains the whole `<section>`/`</section>` block.
2. Use a more descriptive variable name such as `enable_news`. Make it configurable from the Hugo site `config/_default/params.yml`. Make the default value `true`.

2023-07-06 07:55 UTC, furkanakkurt1335 commented
> 1. It is better if the `if` block contains the whole `<section>`/`</section>` block.

I think this causes the layout to change when there are news or not. Events would be shown on the left when there are news, on the right otherwise.

---

> 2. Use a more descriptive variable name such as `enable_news`. Make it configurable from the Hugo site `config/_default/params.yml`. Make the default value `true`.

I will add this, as per the issue #2, as extra to the currently proposed condition of `$news`. The committed condition here is just like the one for the events.

2023-07-06 17:46 UTC, furkanakkurt1335 commented
The changes don't work currently, I'll handle it soon.

2023-07-07 19:44 UTC, furkanakkurt1335 commented
It turns out they work but the config needs to be updated in the `website` side: `bouncmpe/website`.

2023-07-08 10:12 UTC, doganulus commented
@furkanakkurt1335 See my comments in the review.

2023-07-08 10:59 UTC, furkanakkurt1335 commented
`newsroom` partial is created and configuration is done in the `hugo.yml` file which seems to be the default name in the documentation. If condition now encapsulates the entire partial. Which comment do you mean?

2023-07-08 11:36 UTC, doganulus commented
> `newsroom` partial is created and configuration is done in the `hugo.yml` file which seems to be the default name in the documentation. If condition now encapsulates the entire partial. Which comment do you mean?

Here one can leave comments on the code line by line:
https://github.com/bouncmpe/hugo-theme-department/pull/1/files/1d476239bb866909d9dc93a5234e92efec2e18eb

2023-07-08 11:43 UTC, furkanakkurt1335 commented
Yes, but I cannot see them, sorry 😅

2023-07-08 12:05 UTC, doganulus commented
Or this one: https://github.com/bouncmpe/hugo-theme-department/pull/1#pullrequestreview-1516020588

2023-07-08 12:10 UTC, furkanakkurt1335 commented
I can't see the review on the codes. I have seen your 2 comments, replied to them and implemented them.

I don't know how I can't see them, maybe a permission issue?

2023-07-08 12:19 UTC, doganulus commented
> I can't see the review on the codes. I have seen your 2 comments, replied to them and implemented them.
> 
> I don't know how I can't see them, maybe a permission issue?

I added inline comments like this one:

> Remove class="col-xl-8" here and call the partial inside a new div block with class="col-xl-8" on the index page.

You must be able to see them on this thread and in the review (files changed).

2023-07-08 12:20 UTC, doganulus requested changes

2023-07-08 12:20 UTC, doganulus commented on layouts/partials/newsroom.html
> +<section id="newsroom" class="col-xl-8">
Remove `class="col-xl-8"` here and call the partial inside a new div block with `class="col-xl-8"` on the index page.

2023-07-08 12:20 UTC, doganulus commented on layouts/index.html
> +        {{ end }}
Wrap it with a `div` block having `class="col-xl-8"`.

2023-07-08 12:20 UTC, doganulus commented on layouts/index.html
>          <section id="event-board" class="col-xl-4 order-xl-5 mb-5">
Let's add an `eventboard` partial as well.

2023-07-08 12:21 UTC, furkanakkurt1335 commented
Only now am I able to see them, even though they are dated 2 days ago, it's weird. Let me have a look now.

2023-07-08 12:38 UTC, furkanakkurt1335 commented on layouts/partials/newsroom.html
> +<section id="newsroom" class="col-xl-8">
done!

2023-07-08 12:38 UTC, furkanakkurt1335 commented on layouts/index.html
> +        {{ end }}
done!

2023-07-08 12:38 UTC, furkanakkurt1335 commented on layouts/index.html
>          <section id="event-board" class="col-xl-4 order-xl-5 mb-5">
done!

2023-07-08 15:05 UTC, merged